# To Do:
# Add working directory

version: "3"

services:
    mongodb:
        image: mongo:4.0.2
        container_name: mongodb-subscription
        ports:
            - "27017:27017"
        volumes:
            - ~/volumes/dega/mongodb-subscription/:/data/db/
    dega-subscription:
        build:
            dockerfile: Dockerfile
            context: .
        container_name: dega-subscription
        restart: always
        # environment:
        #     - MONGODB_URI=192.168.43.173:27017
        ports:
            - "8081:8081"
        command: "npm run start"
        depends_on:
          - mongodb
